### ISSUE TITLE
Firefox 57 no longer support this

### ISSUE THREAD

**Issue by sameer-kumar-jain** [lazierthanthou/sqlite-manager#93]
Hey,

Just got Firefox 57 on my system and they have now disabled this extension because it doesn't meet their standard. Would it be possible for you to update this?
Thanks a mil in advance

**Comment by justinclift** [comment]
@sameerjain Just to point out, this has been requested already several times. :wink:

The first (main) discussion for it is in #75.  If you still need to use this extension, you'll need to keep on a version of Firefox earlier than 57.  Firefox ESR (Extended Support Release) might be your best option as that's still based on v52, and will be until mid-next year (the link is in #75), otherwise you'll need to look for an alternative way to do SQLite stuff. :smile:

**Comment by sameer-kumar-jain** [comment]
@justinclift ah sorry for duplicates. I just installed v56 and sqlite is back. Thanks a mil

**Comment by justinclift** [comment]
No worries. :smile:
